Repository abirbhattacharya82/Hacktoberfest-Codedump, pull requests merged in 2021-10, with the labels that each got.

#25 Create starsPrinting
  starsPrinting
Labels: good first issue, hacktoberfest

#28 Add Infinite Loop Printing
  Infinite Loop
Labels: good first issue, hacktoberfest

#27 Create pascal.cpp
  Pascals Triangle/pascal.cpp
Labels: hacktoberfest

#62 Added Newton's Method to compute roots Issue#56
  Numerical Computing/Newtons_Method.c
Labels: hacktoberfest

#76 Added Linear search
  Searching_Methods/linear Search.cpp
Labels: hacktoberfest

#75 Bubble sort in Python
  Sorting_Methods/BubbleSort.py
Labels: hacktoberfest

#74 Create linear search file
  Linear Search in c++/linear search
Labels: hacktoberfest

#77 Added Selection Sort
  Sorting_Methods/selection_sort.cpp
Labels: hacktoberfest

#78 Create Star Pattern
  Star Pattern
Labels: good first issue, hacktoberfest

#91 Added binary search in C++
  Binary Search/binarySearch.cpp
Labels: hacktoberfest

#88 Created inverted pyramid of descending numbers
  Star Pattern/Inverted Pyramid of Descending Numbers.py
Labels: bug

#86 Create Alphabetic Pattern
  Star Pattern/Alphabetic Pattern.py
Labels: bug

#85 Proposed a new file in Star Pattern
  Star Pattern/Diamond Pattern.py
Labels: bug

#83 Create Full Pyramid pattern
  Star Pattern/Full Pyramid pattern.py
Labels: bug

#94 QuickSort
  Sorting_Methods/QuickSort.c
Labels: hacktoberfest

#95 Update README.md
  README.md
Labels: hacktoberfest
